import React, { useState } from 'react';
import { Search, BookOpen, Target, TrendingUp, DollarSign, BarChart3, Shield, Zap } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { StockCard } from '@/components/ui/stock-card';

interface GlossaryTerm {
  term: string;
  definition: string;
  category: 'valuation' | 'fundamentals' | 'market' | 'ratios' | 'general';
  example?: string;
}

const glossaryTerms: GlossaryTerm[] = [
  {
    term: "DCF (Discounted Cash Flow)",
    definition: "A valuation method that estimates a company's value by forecasting its future cash flows and discounting them to present value using a discount rate.",
    category: "valuation",
    example: "If a company generates $100M annually and grows at 5% with a 10% discount rate, its DCF value considers all future cash flows."
  },
  {
    term: "Free Cash Flow",
    definition: "The cash a company generates after accounting for cash outflows to support operations and maintain capital assets.",
    category: "fundamentals",
    example: "Operating cash flow of $500M minus capital expenditures of $100M = $400M free cash flow."
  },
  {
    term: "Discount Rate",
    definition: "The interest rate used to calculate the present value of future cash flows, reflecting the investment's risk and opportunity cost.",
    category: "valuation",
    example: "A 10% discount rate means $100 received next year is worth $90.91 today."
  },
  {
    term: "P/E Ratio",
    definition: "Price-to-Earnings ratio compares a company's stock price to its earnings per share, showing how much investors pay for each dollar of earnings.",
    category: "ratios",
    example: "Stock price $50 ÷ EPS $5 = P/E ratio of 10x"
  },
  {
    term: "Market Cap",
    definition: "The total market value of a company's outstanding shares, calculated by multiplying share price by number of shares.",
    category: "market",
    example: "1 billion shares × $50 per share = $50 billion market cap"
  },
  {
    term: "Revenue",
    definition: "The total amount of income generated by a company from its business operations before any expenses are deducted.",
    category: "fundamentals",
    example: "Apple's revenue includes iPhone sales, services, and other product sales."
  },
  {
    term: "Gross Margin",
    definition: "The percentage of revenue remaining after subtracting the cost of goods sold, indicating pricing power and efficiency.",
    category: "ratios",
    example: "Revenue $1000 - COGS $600 = $400 gross profit. Gross margin = 40%"
  },
  {
    term: "EBITDA",
    definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization. A measure of operational profitability.",
    category: "fundamentals",
    example: "Net income + interest + taxes + depreciation + amortization = EBITDA"
  },
  {
    term: "Beta",
    definition: "A measure of a stock's volatility compared to the overall market. Beta of 1 moves with market, >1 is more volatile, <1 is less volatile.",
    category: "market",
    example: "Beta of 1.5 means the stock typically moves 50% more than the market."
  },
  {
    term: "Dividend Yield",
    definition: "Annual dividends per share divided by stock price, showing the percentage return from dividends alone.",
    category: "ratios",
    example: "$2 annual dividend ÷ $50 stock price = 4% dividend yield"
  },
  {
    term: "Book Value",
    definition: "The net value of a company according to its balance sheet, calculated as total assets minus total liabilities.",
    category: "fundamentals",
    example: "Assets $500M - Liabilities $300M = $200M book value"
  },
  {
    term: "ROE (Return on Equity)",
    definition: "Net income divided by shareholders' equity, measuring how effectively a company uses shareholder investments to generate profit.",
    category: "ratios",
    example: "Net income $50M ÷ Shareholders' equity $250M = 20% ROE"
  },
  {
    term: "Working Capital",
    definition: "Current assets minus current liabilities, indicating a company's short-term financial health and operational efficiency.",
    category: "fundamentals",
    example: "Current assets $200M - Current liabilities $100M = $100M working capital"
  },
  {
    term: "Terminal Value",
    definition: "The value of a business beyond the forecast period in a DCF analysis, often calculated using a perpetuity growth model.",
    category: "valuation",
    example: "If final year FCF is $100M growing at 2% forever with 10% discount rate: $100M × 1.02 ÷ (0.10 - 0.02) = $1.275B"
  },
  {
    term: "Intrinsic Value",
    definition: "The actual worth of a company based on fundamental analysis, independent of its current market price.",
    category: "valuation",
    example: "DCF analysis shows intrinsic value of $45 per share vs. current price of $40 = undervalued"
  },
  {
    term: "Bull Market",
    definition: "A period of rising stock prices and investor optimism, typically defined as a 20% increase from recent lows.",
    category: "market",
    example: "The 2010-2020 decade was largely a bull market with consistent upward trends."
  },
  {
    term: "Bear Market",
    definition: "A period of declining stock prices and pessimism, typically defined as a 20% decrease from recent highs.",
    category: "market",
    example: "The 2008 financial crisis created a bear market with widespread declines."
  },
  {
    term: "Volatility",
    definition: "The degree of variation in a stock's price over time, measuring investment risk and price unpredictability.",
    category: "market",
    example: "High volatility stocks can swing 10%+ daily, while low volatility stocks move 1-2%."
  }
];

const categoryIcons = {
  valuation: Target,
  fundamentals: BarChart3,
  market: TrendingUp,
  ratios: DollarSign,
  general: BookOpen
};

const categoryColors = {
  valuation: 'bg-primary/10 text-primary border-primary/20',
  fundamentals: 'bg-success/10 text-success border-success/20',
  market: 'bg-warning/10 text-warning border-warning/20',
  ratios: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
  general: 'bg-muted text-muted-foreground border-border'
};

export const Glossary: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');

  const filteredTerms = glossaryTerms.filter(term => {
    const matchesSearch = term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         term.definition.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'all' || term.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const categories = [
    { key: 'all', label: 'All Terms', count: glossaryTerms.length },
    { key: 'valuation', label: 'Valuation', count: glossaryTerms.filter(t => t.category === 'valuation').length },
    { key: 'fundamentals', label: 'Fundamentals', count: glossaryTerms.filter(t => t.category === 'fundamentals').length },
    { key: 'market', label: 'Market', count: glossaryTerms.filter(t => t.category === 'market').length },
    { key: 'ratios', label: 'Ratios', count: glossaryTerms.filter(t => t.category === 'ratios').length }
  ];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center">
        <div className="flex justify-center mb-4">
          <BookOpen className="h-12 w-12 text-primary" />
        </div>
        <h1 className="text-4xl font-bold mb-4">Financial Glossary</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Master the language of investing with clear explanations of key financial terms and concepts.
        </p>
      </div>

      {/* Search and Filters */}
      <StockCard className="max-w-4xl mx-auto">
        <div className="space-y-4">
          <div className="relative">
            <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search for financial terms..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          
          <div className="flex flex-wrap gap-2">
            {categories.map(category => {
              const Icon = category.key === 'all' ? BookOpen : categoryIcons[category.key as keyof typeof categoryIcons];
              return (
                <Badge
                  key={category.key}
                  variant={selectedCategory === category.key ? "default" : "outline"}
                  className="cursor-pointer hover:bg-primary/20 transition-colors"
                  onClick={() => setSelectedCategory(category.key)}
                >
                  <Icon className="h-3 w-3 mr-1" />
                  {category.label} ({category.count})
                </Badge>
              );
            })}
          </div>
        </div>
      </StockCard>

      {/* Results Count */}
      <div className="text-center text-muted-foreground">
        {filteredTerms.length} term{filteredTerms.length !== 1 ? 's' : ''} found
      </div>

      {/* Terms Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredTerms.map((term, index) => {
          const Icon = categoryIcons[term.category];
          return (
            <Card key={term.term} className="hover:shadow-glow transition-all duration-300">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <CardTitle className="text-lg flex items-center gap-2">
                      <Icon className="h-5 w-5 text-primary" />
                      {term.term}
                    </CardTitle>
                  </div>
                  <Badge 
                    className={categoryColors[term.category]}
                    variant="outline"
                  >
                    {term.category}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                <p className="text-muted-foreground leading-relaxed">
                  {term.definition}
                </p>
                {term.example && (
                  <div className="bg-muted/50 rounded-lg p-3 border-l-4 border-primary">
                    <p className="text-sm">
                      <span className="font-semibold text-primary">Example:</span>{' '}
                      {term.example}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>

      {filteredTerms.length === 0 && (
        <div className="text-center py-12">
          <Search className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold mb-2">No terms found</h3>
          <p className="text-muted-foreground">
            Try adjusting your search or selecting a different category.
          </p>
        </div>
      )}

      {/* Learning Tip */}
      <StockCard variant="highlight" className="max-w-4xl mx-auto text-center">
        <div className="flex justify-center mb-4">
          <Zap className="h-8 w-8 text-primary" />
        </div>
        <h3 className="text-xl font-bold mb-2">Pro Tip</h3>
        <p className="text-muted-foreground">
          Understanding these terms will help you make better investment decisions. 
          Start with the basics like P/E ratio and market cap, then work your way up to DCF analysis.
        </p>
      </StockCard>
    </div>
  );
};